start-at-login = true

after-login-command = []

after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

[key-mapping]
preset = 'qwerty'

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id= 'com.1password.1password'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id= 'com.google.Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'


[mode.main.binding]
ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-t = 'workspace T'

ctrl-slash = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-t = 'move-node-to-workspace T'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
