syntax = "Luau"  # Explicit syntax for modern Lua/Luau projects[3][8]
column_width = 80  # Standard line length for readability[2][3]
line_endings = "Unix"  # Consistent with Linux/macOS environments[3][5]
indent_type = "Spaces"  # Modern preference over tabs[1][3]
indent_width = 2  # Common Lua convention[3][5]

quote_style = "AutoPreferDouble"  # Smart quote selection[3][5]
call_parentheses = "NoSingleString"  # Cleaner syntax for single-string args[3][8]
collapse_simple_statement = "Never"  # Explicit code structure[3][8]
space_after_function_names = "Never"  # Compact function calls[3][5]

[sort_requires]
enabled = false  # Maintain manual require order[3]
