[colors]
# TODO: finish modifying all variables
ansi = [
  "#000000", # black
  "#ff5555", # red
  "#50fa7b", # green
  "#f1fa8c", # yellow
  "#bd93f9", # blue
  "#ff79c6", # magenta
  "#8be9fd", # cyan
  "#bbbbbb"  # white
]

brights = [
  "#44475a", # bright black
  "#ff6e6e", # bright red
  "#69ff94", # bright green
  "#ffffa5", # bright yellow
  "#d6acff", # bright blue
  "#ff92df", # bright magenta
  "#a4ffff", # bright cyan
  "#ffffff"  # bright white
]

background = "{background}"
foreground = "{foreground}"
cursor_bg = "#f8f8f2"
cursor_fg = "#282a36"
cursor_border = "#f8f8f2"
selection_bg = "#44475a"
selection_fg = "#f8f8f2"
